# Generated by Django 3.2.5 on 2021-07-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210721_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('staff', 'Can access backend'),)},
        ),
    ]
