# Generated by Django 3.2.5 on 2021-08-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_of_address', models.CharField(max_length=200)),
                ('seccond_line_of_address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=200, null=True)),
                ('default_address', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shippingaddress'),
        ),
    ]
