# Generated by Django 3.2.5 on 2021-08-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_alter_order_shipping_address'),
        ('accounts', '0006_auto_20210814_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
