# Generated by Django 3.2.5 on 2021-08-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddressmodel',
            name='default_address',
        ),
    ]
