# Generated by Django 3.2.5 on 2021-07-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('barcode', models.CharField(max_length=13)),
                ('price', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('visible', models.BooleanField(default=True)),
                ('coverImage', models.ImageField(upload_to='bookCovers')),
            ],
        ),
    ]
