# Generated by Django 3.2.5 on 2021-07-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20210728_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
