# Generated by Django 3.2.5 on 2021-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
