# Generated by Django 3.2.5 on 2021-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_auto_20210805_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
