# Generated by Django 3.2.5 on 2021-08-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_alter_book_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_of_address', models.CharField(max_length=200)),
                ('seccond_line_of_address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=8)),
                ('is_billing_address', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.shippingaddress'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
