# Generated by Django 3.2.5 on 2021-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_rename_address_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
