# Generated by Django 3.2.5 on 2021-08-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_shippingaddress_default_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_of_address', models.CharField(max_length=200)),
                ('seccond_line_of_address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=200, null=True)),
                ('default_address', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.billingaddress'),
        ),
    ]
