# Generated by Django 3.2.5 on 2021-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_auto_20210810_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
