# Generated by Django 3.2.5 on 2021-08-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_book_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='product_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
