# Generated by Django 3.2.5 on 2021-08-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210814_1958'),
        ('Inventory', '0024_rename_trasaction_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shippingaddress'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
